export interface SymbolMargin {
  symbol: string;
  margin: number;
}

export const symbols: SymbolMargin[] = [
  { symbol: 'BTC', margin: 1.5 },
  { symbol: 'ETH', margin: 2.3 },
  { symbol: 'XRP', margin: 1.7 },
  { symbol: 'BCH', margin: 2.0 },
  { symbol: 'UPT', margin: 1.2 },
  { symbol: 'LTC', margin: 1.2 },
  { symbol: 'ONT', margin: 1.8 },
  { symbol: 'TRX', margin: 1.6 },
  { symbol: 'WBTC', margin: 2.5 },
  { symbol: 'LINK', margin: 2.4 },
  { symbol: 'BAT', margin: 2.1 },
  { symbol: 'HOT', margin: 1.9 },
  { symbol: 'DOGE', margin: 4.2 },
  { symbol: 'ATOM', margin: 1.8 },
  { symbol: 'FTM', margin: 2.7 },
  { symbol: 'MATIC', margin: 2.5 },
  { symbol: 'GALA', margin: 2.2 },
  { symbol: 'SHIB', margin: 3.5 },
  { symbol: 'ROSE', margin: 1.7 },
  { symbol: 'CAKE', margin: 2.3 },
  { symbol: 'YFI', margin: 3.0 },
  { symbol: 'SUSHI', margin: 2.6 },
  { symbol: 'DYDX', margin: 2.8 },
  { symbol: 'LUNA', margin: 2.0 },
  { symbol: '1INCH', margin: 1.8 },
  { symbol: 'COMP', margin: 2.1 },
  { symbol: 'QNT', margin: 2.3 },
  { symbol: 'PAXG', margin: 2.2 },
  { symbol: 'UNI', margin: 2.4 },
  { symbol: 'MKR', margin: 2.7 },
  { symbol: 'ONE', margin: 2.1 },
  { symbol: 'FLOW', margin: 2.2 },
  { symbol: 'CELO', margin: 2.5 },
  { symbol: 'ADA', margin: 2.1 },
  { symbol: 'RDNT', margin: 1.9 },
  { symbol: 'VET', margin: 1.5 },
  { symbol: 'EGLD', margin: 2.6 },
  { symbol: 'ALGO', margin: 2.2 },
  { symbol: 'USDC', margin: 1.4 },
  { symbol: 'XLM', margin: 1.3 },
  { symbol: 'SOL', margin: 3.0 },
  { symbol: 'BNB', margin: 2.9 },
  { symbol: 'WAVES', margin: 2.4 },
  { symbol: 'FLM', margin: 1.8 },
  { symbol: 'ZEN', margin: 2.1 },
  { symbol: 'SAND', margin: 2.7 },
  { symbol: 'BUSD', margin: 1.9 },
  { symbol: 'ARB', margin: 2.3 },
  { symbol: 'SNX', margin: 2.4 },
  { symbol: 'TUSD', margin: 1.7 },
  { symbol: 'NEO', margin: 2.0 },
  { symbol: 'APT', margin: 2.5 },
];
